### ISSUE TITLE
General touchup

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#113]
DOD : 

- [x] Change conviction voting by disputable voting (in Help tooltip in challenge-modal.tsx)
- [x] Change app title : Quest -> Quests
- [x] QuestList need to be scrollable even if the mouse is anywhere in the screen (right know if mouse over filter, it dosnt scroll)
- [x] Add a footer with similar to gardens : ![image.png](https://images.zenhubusercontent.com/608ac1af9468077230c155b4/d2260ae3-b134-4b40-b700-eea21cb68fb2)
- [x] Move **report bug** in footer instead

**Comment by alexchan0394** [comment]
Footer Community -> put everything + link
             Documentation -> wiki
             Feedback -> Report a Bug
![footer-quest](https://user-images.githubusercontent.com/47338497/149637641-f636678d-ddc7-471f-91ad-1053549a2a8e.png)

**Comment by alexchan0394** [comment]
After adding a footer, add the px to scrollThreshold="50px" in quest-list.tsx
