### ISSUE TITLE
Fix dependencies & deprecated

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#15]
DOD : 
- critical severity
- high severity

**Comment by Corantin** [comment]
https://github.com/1Hive/quests/security/dependabot

**Comment by alexchan0394** [comment]
ansi-html@0.0.7 no fix

**Comment by alexchan0394** [comment]
1. Find the librairies that are vulnereble if they are in package.json and yarn.lock
    but not only in yarn.lock (because they are used by something else)
2. Change the version of the library in package.json
3. Deete node_modules
4. Do yarn
5. *Test one by one on the app for good functionnality*
