### ISSUE TITLE
Quest like figma

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#187]
DOD : 

- [ ] Have the same structure as the mock
- [ ] Get the $ value of the quest bounty

Excluded from mock (don't make it): 
- Top left Tag (design)
- Two quests per row

https://www.figma.com/file/eIu9GyVkh9QJfVVxEpkdeM/Quest-Redesign?node-id=158%3A300
![image.png](https://images.zenhubusercontent.com/608ac1af9468077230c155b4/44d82fde-9944-4b70-bbef-a777d13fb5f2)

**Comment by kamikazebr** [comment]
So it will keep one Quest per row?

**Comment by Corantin** [comment]
I guess we can have two columns for large resolutions
