### ISSUE TITLE
[Bug/Feature] Identify if using allowed network

### ISSUE THREAD

**Issue by kamikazebr** [1Hive/quests#197]
If you change your network in Metamask the app dont inform and the next request will fail

![image.png](https://images.zenhubusercontent.com/61b8ceae3404d877db3642c6/226787ea-7162-42a1-bbf0-cf5890a669a6)

Maybe the approach here its UI change and inform Metamask have changed the network and put one button to change the network, more likely with the new version the Gardens UI.

Some reference here.
https://github.com/1Hive/gardens-ui/pull/825.

More simply way its just inform we are incorrect network and let the user decide what todo. Like the image below

[Uploading... image.png]

**Comment by Corantin** [comment]
We have only one production network (xdai) so we might bump this to Icebox (to be discussed with the team)

**Comment by kamikazebr** [comment]
That https://github.com/1Hive/quests/pull/207 take that.

**Comment by Corantin** [comment]
The bug is fixed but it could be nice to have a rinkeby version to let people test the app if they are not sure of how to use it
