### ISSUE TITLE
Optimize api calls

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#202]
- [ ] Have a token price cache to not requery the same token price for each quest having the same token
- [ ] Dashboard should use the cache
- [ ] Each quest should use the cache

**Comment by kamikazebr** [comment]
Looks like the #255 solves it

**Comment by Corantin** [comment]
Nice, I saw that the api no longers have MAX CALL REACHED problem. But it might be better if we don't query the same token price for each quest having the same token + total for dashboard

**Comment by kamikazebr** [comment]
> But it might be better if we don't query the same token price for each quest having the same token

What you mean? I think already done that. I create new list without the duplicates token prices.

**Comment by Corantin** [comment]
> > But it might be better if we don't query the same token price for each quest having the same token
> 
> What you mean? I think already done that. I create new list without the duplicates token prices.

I was talking about quest list not dashboard
