### ISSUE TITLE
Quest list 2 columns

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#208]
DOD : 
- [x] Make sure they are the same height
- [x] Do not include blocks in the summary view
- [x] Warn Creator for the description that only the first 5 (use var) lines will be displayed in summary view 
- [x] Don't show the links in the summary (just a normal text)
- [ ] Add max-height on wrapper description

**Comment by alexchan0394** [comment]
Warning : "Only 5 first lines will be shown in the summary."

**Comment by alexchan0394** [comment]
use !isSummary in collapse-block

**Comment by alexchan0394** [comment]
NormalizedHtml___StyledDiv-sc-1lqp1vn-0 UjkFY

max-height: 179px;
