### ISSUE TITLE
Bug : Claim list problem with button executing the wrong claim

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#212]
Repro : 
- Open quest details
- Schedule a claim
- Wait for this claim to be executable (wait for 20 min)
- Refresh and make sure the claim button is visible
- Schedule another claim
- Wait for this claim to be displayed without refreshing

DOD : 
- [x] Fix the bug
- [x] Order claims chronological (see comments)

**Comment by kamikazebr** [comment]
![image.png](https://images.zenhubusercontent.com/61b8ceae3404d877db3642c6/a3fda3d6-adac-42c5-aa57-d6c67dcd6e9a)

i'm testing it.

Btw the claim list shouldnt be in some kind the order, for example the last claim in the top/bottom?

**Comment by Corantin** [comment]
Yeah we should add this ![image.png](https://images.zenhubusercontent.com/608ac1af9468077230c155b4/8b2654e1-f58f-4b51-8007-e3cfd0aaea8e)
