### ISSUE TITLE
Bug overflow amount field input too big need ellipsis

### ISSUE THREAD

**Issue by Corantin** [1Hive/quests#270]
- [x] If too big, should show ...
- [x] Add the number in [title HTML attribute](https://www.w3schools.com/tags/att_global_title.asp#:~:text=HTML%20title%20Attribute&text=The%20title%20attribute%20specifies%20extra,validate%20on%20any%20HTML%20element.) to be able to display it on hover

![image.png](https://images.zenhubusercontent.com/608ac1af9468077230c155b4/78327b0d-d05f-4310-b17f-1a8dba4c77c1)

**Comment by alexchan0394** [comment]
NOTE : 

const AmountTextInputStyled = styled(TextInput)`
  flex-grow: 1;
  ${({ wide }: any) => (wide ? '' : `max-width: 200px;`)}
  text-overflow: ellipsis;
`;
