### ISSUE TITLE
Bug : I can Claim Quests that I didn't create 

### ISSUE THREAD

**Issue by pglavin2** [1Hive/quests#300]
**Describe the bug**
Like the title says, I can Claim Quests that I didn't create, and they seem to execute.

**To Reproduce**

1. Go to a Quest you didn't create that has a Claim scheduled
2. Click on "Claim"
3. Confirm transactions in Metamask
4. Claim is Executed in the interface

**Expected behavior**
I would've expected the "Claim" button not to be visible for Quests I didn't create

**Screenshots**
![Screen Shot 2022-05-31 at 3 40 57 PM](https://user-images.githubusercontent.com/9218761/171295732-5e311a00-14f0-4b22-9003-7909d9fc6149.png)
![Screen Shot 2022-05-31 at 3 35 51 PM](https://user-images.githubusercontent.com/9218761/171295750-ba50af40-7552-4593-9111-84c0053ea39c.png)
![Screen Shot 2022-05-31 at 3 35 11 PM](https://user-images.githubusercontent.com/9218761/171295753-3cd335e3-450f-4fde-8b8e-d2bbc3a4c374.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra v10.13.6
- Browser:  Chrome
- Version:  101.0.4951.64 (Official Build) (x86_64)

**Comment by Corantin** [comment]
If the Quest you claimed is expired, it's intended to let other users execute it (so the creator doesn't have to wait for the player to execute it for reclaiming the remaining funds and deposit). But the warning message is definitely misleading here. Could be better to have something like "Only a stakeholder of this Quest may execute this claim". And in the best world, the Player would be notified (email or internal app notification) if the claim is executed so he knows that the reward as been sent to his wallet.

**Comment by pglavin2** [comment]
Maybe a better question is who is NOT allowed to execute a claim when its expired? If everyone can execute it, then I'd think you'd just say "Anyone can execute this claim on behalf of the person that created it."

**Comment by Corantin** [comment]
Yes everyone can execute it when the delay is over (even if the Quest is not expired). However, I want the UI to communicate that only the player should execute it because that way he knows that the reward should be in his wallet. The reason, the UI shows it for everyone when the Quest is expired is to let the Creator execute it without waiting for the Player (so he can reclaim his deposit and the remaining funds)

**Comment by x0oo11235oo0x** [comment]
That makes sense I wasn't sure what to think as I'm still new around here :) thanks for the clarity on this and I agree
