### ISSUE TITLE
Bug : Grammar error near 'expire time'

### ISSUE THREAD

**Issue by anarayan131** [1Hive/quests#330]
**Describe the bug**
When hovering the mouse over the exclamation mark near the 'expire time' option, it displays 'will show all quests that are not expired this date'. This is gramatically incorrect. The correct alternative is 'will show all questions that are not expired until this date' OR 'will show all unexpired quests until this date'.

**To Reproduce**
1. Go to 'https://quests.1hive.org' in RInkeby
2. Hover the mouse over the exclamation mark near the 'expire time' option
3. The spelling error is in the text that pops up

**Screenshots**
Uploaded. The text is highlighted in red marking. 

![spellingerror](https://user-images.githubusercontent.com/67418730/175506373-0b01d19c-9d83-42e6-8712-07a528edd4ff.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser - brave
- Version - 1.39

**Comment by Corantin** [comment]
Thx  for submitting this we all are french newby in English and we always need guys like you :p
If you want you can claim a reward for that one here when the HNY lock is fixed : 
https://quests.1hive.org/detail?id=0xAC979eacb1738f77d107c66F45B0E0CF6122de6A&chainId=100
Don't worry if the quest is expired you still can claim it and I will not withdraw the funds since during the event, HNY was locked.

**Comment by anarayan131** [comment]
> 
Glad I could be of some help. Keep up the good work. I am a fan :)
Perhaps a silly question - can you claim the HNY without having a deposit of 0.1 HNY in my wallet? I dont really hold any HNY as of now

**Comment by Corantin** [comment]
No sorry the contract requires a deposit to be able to claim but I can understand that staking 0.1 HNY to be able to earn 0.05 HNY is a bit weird

**Comment by Corantin** [comment]
What is your wallet address ?

**Comment by Corantin** [comment]
I can claim it for you and you will receive it once the validation delay is over

**Comment by Corantin** [comment]
https://github.com/1Hive/quests/commit/c0c6f9c80e0df930ba860ac9f3981534b0a3a22e

**Comment by anarayan131** [comment]
Here is my Gnosis wallet address - 0x173BDe3914135424f5C260973B45551332E6DD33

Thank you for your help :)

**Comment by Corantin** [comment]
You should come back in 7 days and execute it :p 
![image](https://user-images.githubusercontent.com/13890618/178762706-c467c925-89da-410d-9b71-4477832ab4a5.png)
Unless someone decides to challenge it

**Comment by anarayan131** [comment]
Thank you for your help. I will remember to claim it a week :)

**Comment by Corantin** [comment]
Hey 1 week later :p If you claim it before 4 days, you will be the first one earning a reward from Quests 🥇 
![image](https://user-images.githubusercontent.com/13890618/180068025-be8a53e8-5722-4d33-80d4-848a4fbaa446.png)

**Comment by Corantin** [comment]
Hey man you are right there is something wrong, problem was that the gas limit was not high enough so it ran out of gas
![image](https://user-images.githubusercontent.com/13890618/180227177-b9245df7-1075-4224-8e2e-436c06130277.png)
I just pushed a change with a higher limit, I tested out with a simulation, and all is supposed to work :p sorry about that

**Comment by anarayan131** [comment]
Now it works. Thanks for your help. I am glad that I was able to identify one more bus ;) If you need someone to play around with some stuff or go though some English language stuff, feel free to contact me.

**Comment by Corantin** [comment]
I will check it out and let you know
